import { db, json, body, requireSession, requestId, rateLimit, requireSameOrigin, id } from '../../lib.mjs';
async function ensureSchema(){await db().query("CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,read BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT now())");await db().query('CREATE INDEX IF NOT EXISTS notifications_user_created_idx ON notifications(user_id,created_at DESC)');}
function cleanPayload(p){return p&&typeof p==='object'?p:{}}
export default async function handler(req,res){const rid=requestId(req);try{const s=requireSession(req,res,[],rid);if(!s)return;if(!['GET','POST','PATCH'].includes(req.method))return json(res,405,{error:'Method not allowed'},rid);if(req.method!=='GET'&&!requireSameOrigin(req,res,rid))return;if(!rateLimit(req,'notifications',60,60000))return json(res,429,{error:'Too many requests'},rid);await ensureSchema();const q=req.query||{};if(req.method==='GET'){const unread=String(q.unread||'')==='true';const limit=Math.min(Math.max(Number(q.limit)||25,1),100);const r=await db().query(`SELECT id,type,payload,read,created_at FROM notifications WHERE user_id=$1 ${unread?'AND read=false':''} ORDER BY created_at DESC LIMIT $2`,[s.id,limit]);return json(res,200,{notifications:r.rows.map(x=>({id:x.id,type:x.type,payload:cleanPayload(x.payload),read:x.read,createdAt:new Date(x.created_at).toISOString()}))},rid);}
const b=await body(req);if(req.method==='POST'&&String(b.action||'')==='send'){if(s.role!=='admin'&&s.role!=='creator')return json(res,403,{error:'Creator/Admin access required'},rid);const title=String(b.title||'').trim().slice(0,160),text=String(b.text||'').trim().slice(0,2000),creatorId=s.role==='creator'?s.id:String(b.creatorId||'');if(!title||!text)return json(res,400,{error:'Title and message are required'},rid);let recipients=[];if(b.userIds&&Array.isArray(b.userIds)){recipients=b.userIds.map(String).filter(Boolean).slice(0,500);}else{const r=creatorId?await db().query(`SELECT DISTINCT u.id FROM users u LEFT JOIN subscriptions sub ON sub.fan_id=u.id AND sub.creator_id=$1 LEFT JOIN chats c ON c.fan_id=u.id AND c.creator_id=$1 WHERE u.role='fan' AND u.status='active' AND (sub.id IS NOT NULL OR c.id IS NOT NULL)`,[creatorId]):await db().query("SELECT id FROM users WHERE role='fan' AND status='active'");recipients=r.rows.map(x=>x.id);}
if(s.role==='creator'){
 const allowed=await db().query(`SELECT DISTINCT u.id FROM users u LEFT JOIN subscriptions sub ON sub.fan_id=u.id AND sub.creator_id=$1 LEFT JOIN chats c ON c.fan_id=u.id AND c.creator_id=$1 WHERE u.role='fan' AND u.status='active' AND (sub.id IS NOT NULL OR c.id IS NOT NULL)`,[s.id]);
 const set=new Set(allowed.rows.map(x=>String(x.id))); recipients=recipients.filter(uid=>set.has(String(uid)));
}if(!recipients.length)return json(res,200,{ok:true,sent:0});const client=await db().connect();try{await client.query('BEGIN');for(const uid of recipients)await client.query('INSERT INTO notifications(id,user_id,type,payload) VALUES($1,$2,$3,$4::jsonb)',[id('notif'),uid,'announcement',JSON.stringify({title,text,icon:'🔔'})]);await client.query('COMMIT');return json(res,200,{ok:true,sent:recipients.length},rid);}catch(e){try{await client.query('ROLLBACK')}catch{};throw e}finally{client.release();}}
if(req.method==='PATCH'){const notificationId=String(b.id||'');if(notificationId){const r=await db().query('UPDATE notifications SET read=true WHERE id=$1 AND user_id=$2 RETURNING id',[notificationId,s.id]);return json(res,200,{ok:true,updated:r.rowCount},rid);}if(b.allRead===true){const r=await db().query('UPDATE notifications SET read=true WHERE user_id=$1 AND read=false',[s.id]);return json(res,200,{ok:true,updated:r.rowCount},rid);}}return json(res,400,{error:'Notification id, allRead, or send action is required'},rid);}catch(e){return json(res,e?.statusCode||500,{error:e?.statusCode?e.message:'Server error'},rid);}}
export async function createNotification(userId,type,payload={}){const r=await db().query('INSERT INTO notifications(id,user_id,type,payload) VALUES($1,$2,$3,$4::jsonb) RETURNING id,type,payload,read,created_at',[id('notif'),userId,String(type).slice(0,120),JSON.stringify(cleanPayload(payload))]);return r.rows[0];}
